/**
 * @file    main.c
 * @brief   EMNODE / RBPS BMS application entry point (runs on U2,
 *          STM32C011D6Yx). Polls U1 (BQ76940) over I2C1, applies the
 *          protection policy, and drives the status LEDs.
 *
 * This assumes a standard STM32CubeMX-generated project where
 * SystemClock_Config(), MX_GPIO_Init(), MX_I2C1_Init() and the HAL_Init()
 * call already exist (either in this file if you let CubeMX regenerate
 * it around this content, or in the CubeMX-owned main.c - in that case
 * just call bms_app_init()/bms_app_run() from inside the generated
 * while(1) loop instead of duplicating HAL bring-up here).
 */
#include "stm32c0xx_hal.h"
#include "bms_config.h"
#include "i2c_bus.h"
#include "bq76940.h"
#include "protection.h"
#include "led_status.h"

/* ---- CubeMX-owned globals (defined in i2c.c / gpio.c normally) ---- */
I2C_HandleTypeDef hi2c1;

/* ---- Prototypes normally generated by CubeMX ---- */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);

/* Polling period for the BQ76940 (cell V / I / temp + fault status). */
#define BMS_POLL_PERIOD_MS   250U

static bool s_afe_ready = false;

void bms_app_init(void)
{
    led_status_init();

    s_afe_ready = (bq76940_init() == BQ_OK);
    if (!s_afe_ready) {
        /* AFE didn't answer on I2C - flag fault immediately, keep the
         * FETs off (their default power-up state is OFF until the MCU
         * explicitly turns them on, so we simply never enable them). */
        led_fault_set(true);
        (void)bq76940_set_charge_fet(false);
        (void)bq76940_set_discharge_fet(false);
    }
}

void bms_app_run_forever(void)
{
    bq_pack_data_t pack;

    for (;;) {
        if (!s_afe_ready) {
            /* Retry bring-up after a transient bus/startup failure. Never
             * permit normal protection logic to enable FETs before init. */
            (void)bq76940_set_charge_fet(false);
            (void)bq76940_set_discharge_fet(false);
            s_afe_ready = (bq76940_init() == BQ_OK);
            HAL_Delay(BMS_POLL_PERIOD_MS);
            continue;
        }

        bq_status_t st = bq76940_read_all(&pack);

        if (st == BQ_OK) {
            protection_evaluate(&pack);
            /* Hook point: push `pack` out over your telemetry link of
             * choice (this board has no UART - J3 is SWD-only - so a
             * typical extension is CAN, or SWD-based RTT logging). */
        } else if (st == BQ_ERR_I2C) {
            /* Communication lost with the AFE - fail safe. */
            bq76940_set_charge_fet(false);
            bq76940_set_discharge_fet(false);
            led_fault_set(true);
        } else if (bq76940_has_fault(&pack)) {
            /* Hardware faults are visible in SYS_STAT even if CC_READY is
             * not set yet, so do not wait for a complete sample to react. */
            (void)bq76940_set_charge_fet(false);
            (void)bq76940_set_discharge_fet(false);
            led_fault_set(true);
        }
        /* BQ_ERR_NOT_READY: conversion just wasn't finished yet, retry
         * next tick - not an error worth latching a fault over. */

        HAL_Delay(BMS_POLL_PERIOD_MS);
    }
}

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C1_Init();

    bms_app_init();
    bms_app_run_forever();
}

/* ---------------------------------------------------------------------
 * The three functions below are placeholders: in a real project these
 * are generated by STM32CubeMX from your .ioc file (clock tree, GPIO
 * alternate functions for PB6/PB7 I2C1, etc). Do not hand-write them
 * from scratch - regenerate with CubeMX and keep bms_app_init()/
 * bms_app_run_forever() as the only calls added to its main().
 * ------------------------------------------------------------------- */
static void SystemClock_Config(void) { /* CubeMX-generated */ }
static void MX_GPIO_Init(void)       { /* CubeMX-generated */ }
static void MX_I2C1_Init(void)       { /* CubeMX-generated */ }
